### ISSUE TITLE
Could openQA run tests on phythical machines

### ISSUE THREAD

**Issue by horseFucker123** [os-autoinst/os-autoinst#1630]
Hi,
  I'm new to openQA，wondered if I could use openQA to test a OS on a phythcial machine ,not on a virtual machine like QEMU backend.If so ,any docs ?

**Comment by okurz** [comment]
Yes, definitely. https://github.com/os-autoinst/os-autoinst/blob/master/doc/backends.md mentions that there are multiple backends. https://github.com/os-autoinst/os-autoinst/tree/master/backend shows all existing backends. I would not recommend to control your main production machine but that should also be possible.

**Comment by horseFucker123** [comment]
> Yes, definitely. https://github.com/os-autoinst/os-autoinst/blob/master/doc/backends.md mentions that there are multiple backends. https://github.com/os-autoinst/os-autoinst/tree/master/backend shows all existing backends. I would not recommend to control your main production machine but that should also be possible.

Hi,okurz
     Thanks for reply,after reading the documentation, I understand that openQA can install physical machines by setting backend to ipmi, but I also wonder if openQA can install physical machines in GUI mode like a virtual machine does. This is because I can manually install physical machines in GUI mode using KVM remote control,that just like what openQA can do in virtual machine .

**Comment by okurz** [comment]
Well, in principle it would be possible to use all remote controls within openQA itself. As far as I am aware though IPMI does not offer ways to display higher resolution graphical output as it mostly only has access to a serial port. A remote KVM might use a different protocol like VNC which openQA can then also use to directly access a machine. The specific parameters to access that remote KVM would need to be known to openQA and os-autoinst though.

**Comment by horseFucker123** [comment]
> Well, in principle it would be possible to use all remote controls within openQA itself. As far as I am aware though IPMI does not offer ways to display higher resolution graphical output as it mostly only has access to a serial port. A remote KVM might use a different protocol like VNC which openQA can then also use to directly access a machine. The specific parameters to access that remote KVM would need to be known to openQA and os-autoinst though.

Got it,maybe  the next thing I need to do is get to know what ipmi parameters my server supports.Anyway，thanks very much

**Comment by okurz** [comment]
You are very much welcome. I hope I could help :)
