### ISSUE TITLE
Add VM snapshot creation to API

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/os-autoinst#192]
It would be great to have API function for creating VM snapshots. For example, when test fails, I would like to create VM snapshot so that I would be able to load it and inspect it further.

**Comment by coolo** [comment]
as the hard discs are thrown away in the normal case, you can do this only temporary. And for a temporary hack do

use bmwqemu;
$bmwqemu::make_snapshot('needtodebugthis');
