### ISSUE TITLE
Is http://r.opensu.se/devel:openQA/r useful now?

### ISSUE THREAD

**Issue by choldrim** [os-autoinst/os-autoinst#200]
As the title: Is http://r.opensu.se/devel:openQA/r useful now in openSUSE setup?
https://github.com/os-autoinst/os-autoinst/blob/master/INSTALL.asciidoc

**Comment by coolo** [comment]
I guess it depends on your distro. on 13.1 it works, on 13.2 and factory it doesn't - most likely because l0ki no longer maintains the site ;(

http://r.opensu.se/devel:openQA/openSUSE_Factory/r works though
