### ISSUE TITLE
DISTRI undefined

### ISSUE THREAD

**Issue by choldrim** [os-autoinst/os-autoinst#201]
\# execute
./isotovideo
\# get the output like this:
DISTRI undefined

the file /tmp/os-autoinst-run/vars.json exits

**Comment by coolo** [comment]
and is in that vars.json a DISTRI?

**Comment by choldrim** [comment]
sorry, I am wrong, I run the isotovideo in the os-autoinst dir, not in  /tmp/os-autoinst-run/vars.json, so, it can't run normally.  I am sorry for this.
