### ISSUE TITLE
TestResult not found

### ISSUE THREAD

**Issue by choldrim** [os-autoinst/os-autoinst#202]
Hi:
I let openQA work in deepin(ubuntu like), and run the isotovideo in the /tmp/os-autoinst dir, which just include one file vars.json.
Q: The results can not be found in http://localhost/tests after running.
Do I need to mv the test result to /var/lib/openqa/testresults or other Dirs?
vars.json:
-------------------------------------------------------------------
{
   "DISTRI" :      "opensuse",
   "CASEDIR" :     "/home/choldrim/misc/dist/os-autoinst/distri/opensuse",
   "NAME" :        "test-name",
   "ISO" :         "/home/choldrim/openSUSE-13.2-KDE-Live-i686.iso",
   "VNC" :         "91",
   "BACKEND" :     "qemu",
   "DESKTOP" :     "kde"
}
-------------------------------------------------------------------
sonsole output:
-------------------------------------------------------------------
usingenv DESKTOP=kde
usingenv DISTRI=opensuse
usingenv QEMUCPUS=1
usingenv INSTLANG=en_US
usingenv QEMUVGA=cirrus
usingenv KDE=1
usingenv ISO=/home/choldrim/openSUSE-13.2-KDE-Live-i686.iso
usingenv QEMUVGA=cirrus
scheduling bootloader /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/bootloader.pm
scheduling welcome /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/welcome.pm
scheduling good_buttons /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/good_buttons.pm
scheduling installation_mode /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/installation_mode.pm
scheduling partitioning /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/partitioning.pm
scheduling partitioning_finish /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/partitioning_finish.pm
scheduling installer_timezone /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/installer_timezone.pm
scheduling logpackages /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/logpackages.pm
scheduling installer_desktopselection /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/installer_desktopselection.pm
scheduling user_settings /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/user_settings.pm
scheduling installation_overview /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/installation_overview.pm
scheduling start_install /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/start_install.pm
scheduling livecdreboot /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/livecdreboot.pm
scheduling first_boot /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/first_boot.pm
scheduling consoletest_setup /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/consoletest_setup.pm
scheduling textinfo /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/textinfo.pm
scheduling hostname /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/hostname.pm
scheduling xorg_vt /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/xorg_vt.pm
scheduling zypper_lr /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/zypper_lr.pm
scheduling zypper_ref /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/zypper_ref.pm
scheduling yast2_lan /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/yast2_lan.pm
scheduling aplay /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/aplay.pm
scheduling glibc_i686 /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/glibc_i686.pm
scheduling zypper_up /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/zypper_up.pm
scheduling zypper_in /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/zypper_in.pm
scheduling yast2_i /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/yast2_i.pm
scheduling yast2_bootloader /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/yast2_bootloader.pm
scheduling sshd /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/sshd.pm
scheduling sshfs /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/sshfs.pm
scheduling mtab /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/mtab.pm
scheduling consoletest_finish /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/console/consoletest_finish.pm
scheduling xterm /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/xterm.pm
scheduling sshxterm /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/sshxterm.pm
scheduling kate /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/kate.pm
scheduling firefox /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/firefox.pm
scheduling firefox_audio /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/firefox_audio.pm
scheduling chromium /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/chromium.pm
scheduling ooffice /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/ooffice.pm
scheduling oomath /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/oomath.pm
scheduling oocalc /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/oocalc.pm
scheduling khelpcenter /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/khelpcenter.pm
scheduling systemsettings /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/systemsettings.pm
scheduling dolphin /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/dolphin.pm
scheduling yast2_users /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/yast2_users.pm
scheduling amarok /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/amarok.pm
scheduling kontact /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/kontact.pm
scheduling reboot_kde_pre /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/reboot_kde_pre.pm
scheduling reboot /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/reboot.pm
scheduling desktop_mainmenu /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/desktop_mainmenu.pm
scheduling inkscape /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/inkscape.pm
scheduling gimp /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/gimp.pm
scheduling gnucash /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/gnucash.pm
scheduling shutdown /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/x11/shutdown.pm
28886: to_child 15, from_child 16
init needles from /home/choldrim/misc/dist/os-autoinst/distri/opensuse/needles
28886: cmdpipe 14, rsppipe 17
started mgmt loop with thread id 1
loaded 0 needles
remove_tree qemuscreenshot
Use of uninitialized value in string eq at /home/choldrim/misc/dist/os-autoinst/backend/qemu.pm line 190.
Formatting 'raid/1', fmt=qcow2 size=10737418240 encryption=off cluster_size=65536 lazy_refcounts=off 
starting: /usr/bin/kvm -serial file:serial0 -soundhw ac97 -global isa-fdc.driveA= -vga cirrus -m 1024 -netdev user,id=qanet0 -device virtio-net,netdev=qanet0,mac=52:54:00:12:34:56 -device virtio-blk,drive=hd1 -drive file=raid/l1,cache=unsafe,if=none,id=hd1 -cdrom /home/choldrim/openSUSE-13.2-KDE-Live-i686.iso -boot once=d,menu=on,splash-time=5000 -device usb-ehci -device usb-tablet -smp 1 -enable-kvm -no-shutdown -vnc :91,share=force-shared -qmp unix:qmp_socket,server,nowait -monitor unix:hmp_socket,server,nowait -S -monitor telnet:127.0.0.1:15222,server,nowait
prot: RFB 003.008

28886: hmpsocket 21, qmpsocket 22
WELCOME QEMU 2.0.0 monitor - type 'help' for more information
EVENT {"timestamp":{"microseconds":576484,"seconds":1425537520},"event":"RESUME"}
pointer type 0 0 640 480 -257

||| starting bootloader tests/installation/bootloader.pm at 2015-03-05 06:38:40
Debug: /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/bootloader.pm:22 called testapi::assert_screen
<<< assert_screen(mustmatch="inst-bootmenu", timeout=15)
NO matching needles for inst-bootmenu
[Thu Mar  5 14:38:40 2015] [info] Listening at "http://*:15223"
Server available at http://127.0.0.1:15223
STAT 15 statuser=0.11 statsystem=0.06  - similarity: 29
STAT 14 statuser=0.11 statsystem=0.06  - similarity: 15.929121726374
STAT 13 statuser=0.16 statsystem=0.08  - similarity: 50.028504689842
STAT 12 statuser=0.17 statsystem=0.08  - similarity: 50.028504689842
STAT 11 statuser=0.17 statsystem=0.08  - similarity: 1000000
STAT 10 statuser=0.17 statsystem=0.09  - similarity: 1000000
STAT 9 statuser=0.22 statsystem=0.13  - similarity: 8.28908589909586
STAT 8 statuser=1.02 statsystem=0.38  - similarity: 33.1638422280664
STAT 7 statuser=1.9 statsystem=0.54  - similarity: 27.4263477982574
no change 6 statuser=2.73 statsystem=0.76 
STAT 5 statuser=3.45 statsystem=1.06  - similarity: 7.94042487715908
no change 4 statuser=4.02 statsystem=1.52 
no change 3 statuser=4.7 statsystem=1.84 
no change 2 statuser=5.31 statsystem=2.23 
no change 1 statuser=5.96 statsystem=2.59 
no change 0 statuser=6.78 statsystem=2.93 
>>> assert_screen: match=inst-bootmenu timed out after 15
Can't exec "optipng": 没有那个文件或目录 at /home/choldrim/misc/dist/os-autoinst/ppmclibs/blib/lib/tinycv.pm line 186.
wrote testresults/first test/template-inst-bootmenu-20150305_063856.json
SAVING 15 29
SAVING 14 15.929121726374
SAVING 9 8.28908589909586
SAVING 7 27.4263477982574
SAVING 5 7.94042487715908
Debug: /home/choldrim/misc/dist/os-autoinst/distri/opensuse//tests/installation/bootloader.pm:22 called testapi::assert_screen
<<< mydie(needle(s) 'inst-bootmenu' not found)
test bootloader died: mydie at /home/choldrim/misc/dist/os-autoinst/testapi.pm line 55.

test bootloader died: 

waitpid for 28893 returned 0
sending TERM to qemu pid: 28893
waitpid for 28893 returned 28893
QEMU: qemu: terminating on signal 15 from pid 28886
sending magic and exit
received magic close
isotovideo done
killing commands thread
done joining commands thread
-------------------------------------------------------------------

**Comment by coolo** [comment]
if you want openQA to display something you need openQA to schedule it and have the openQA worker  run isotovideo. What you're trying doesn't work as is

**Comment by choldrim** [comment]
yes, it has openQA running workers
start script:
/usr/share/openqa/script/worker --instance 1 --apikey 187CDF447XXXXXX --apisecret E83B5325A6XXXXX --isotovideo /home/openqa/os-autoinst/isotovideo --verbose

output:
------------------------------------------------------------------------------------------------
POST http://localhost/api/v1/workers?host=choldrim-lt&backend=qemu&instance=2&mem_max=5810&cpu_arch=x86_64&cpu_opmode=32-bit,+64-bit
WEBSOCKET ws://localhost/api/v1/workers/3/ws
## adding timer ws_keepalive
## adding timer check_job
checking for job ...
POST http://localhost/api/v1/workers/3/grab_job?host=choldrim-lt&backend=qemu&instance=2&mem_max=5810&cpu_arch=x86_64&cpu_opmode=32-bit,+64-bit
checking for job ...
POST http://localhost/api/v1/workers/3/grab_job?host=choldrim-lt&backend=qemu&instance=2&mem_max=5810&cpu_arch=x86_64&cpu_opmode=32-bit,+64-bit
------------------------------------------------------------------------------------------------
and I open the url:
http://localhost/api/v1/workers/3/grab_job?host=choldrim-lt&backend=qemu&instance=2&mem_max=5810&cpu_arch=x86_64&cpu_opmode=32-bit,+64-bit
I get:
![deepinscreenshot20150305152716](https://cloud.githubusercontent.com/assets/6734555/6500864/20f344c0-c34c-11e4-93b8-32a4bdaf2ba9.png)

I am a novice, and I have checked this problem for hours, really don't know where I get wrong...

**Comment by coolo** [comment]
did you read any openQA documentation? if you edit your own vars.json you can forget about openQA at all - if you want openQA, you have to use openQA and not isotovideo.

**Comment by choldrim** [comment]
Yes, I did.
Ok, clarify my question:
if I use openQA not isotovideo, where the vars.json should be placed?

I think I still need you hellp. so sorry for my trouble.  :(

**Comment by aaannz** [comment]
You don't need to handle vars.json, it is handled by OpenQA-Worker. Once you schedule job in OpenQA-WebUi, Worker will take it automatically and you don't need to worry about running isotovideo or files.

**Comment by choldrim** [comment]
THANKS A LOTS. I know all suddenly!!  
thanks again!  :+1:    :D
