### ISSUE TITLE
Mouse location interface?

### ISSUE THREAD

**Issue by choldrim** [os-autoinst/os-autoinst#218]
Is there any interface to get mouse location  in os-autoinst?
I have checked the os-autoinst source code and the Net::VNC api, but  I couldn't find any interface to get the mouse location.
I want to get the mouse info with some shell cmds through "script_output", but I get:
```shell
>>> wait_serial: curl-0: fail
test WelcomeGuid died: script couldn't be downloaded at /home/deepin/misc/dist/os-autoinst/testapi.pm line 390.
```
it seems that the interface "script_output" may not fit all distri.

well, have you done similar situation, or give me some better adivse?  ;)

**Comment by coolo** [comment]
could you please not open issues for questions please? drop into #opensuse-factory on IRC instead

**Comment by choldrim** [comment]
Sorry.
