### ISSUE TITLE
Add possibility to specify where to click in needle

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/os-autoinst#224]
I think that user should be able to specify coordinates of where to click in needle. From what I understand, when there are more areas to match in one needle, `assert_and_click` uses the smallest one. I think that better approach is to be able to specify another area with type `click`. When `assert_and_click` is called with this needle, it checks if `click` area is present and clicks on that coordinates, falling back to clicking on smallest area when there is no `click` area specified.

**Comment by okurz** [comment]
@garretraziel What would be the benefit to have a second approach? Are you still interested in this?

**Comment by garretraziel** [comment]
TBH, we found out that this isn't really that much of a problem. When ambiguous (e. g. there are several match areas and it isn't clear which one is the smallest), we use two needles (one for match, second for click). So this would be nice to have, but not really necessary.

**Comment by okurz** [comment]
@coolo please close then

**Comment by sysrich** [comment]
@okurz I am not @coolo, but I will close, mwuhahahaha
