### ISSUE TITLE
Add s390x support to QEMU backend

### ISSUE THREAD

**Issue by LKHN** [os-autoinst/os-autoinst#2312]
Hi!

First and foremost, I would want to thank everyone who contributed to this project.

In AlmaLinux OS, We are started to doing the tests with openQA in 4 architecture; `x86_64`, `AArch64`, `ppc64le` and `s390x`.

For `s390x`, we currently building our patched version of openQA and os-autoinst RPMs. 

I would like to introduce our list of patches we use to tests our `s390x` builds on openqa.almalinux.org.

* Add Enterprise Linux support to the QEMU backend (Merged) - https://github.com/os-autoinst/os-autoinst/pull/2268
* Add s390x support to QEMU backend (to create a VM)- https://github.com/os-autoinst/os-autoinst/pull/2309
* Add support for serial device of `s390x` in `testapi` (to run console based tests) - https://github.com/os-autoinst/os-autoinst/pull/2310
* Enable VNC endian conversion when worker is big-endian (two have correct colors for needles matching) - https://github.com/os-autoinst/os-autoinst/pull/2311
* Make serialization of test results portable(to be able to upload asset/artifacts https://github.com/os-autoinst/openQA/pull/5108

An test which does full installation of OS with GUI available on https://openqa.almalinux.org/tests/2601 

The machine settings:

```
ARCH=s390x
CDMODEL=scsi-cd
HDDMODEL=virtio-blk
MAX_JOB_TIME=36000
QEMUCPU=host
QEMUCPUS=2
QEMUMACHINE=s390-ccw-virtio
QEMURAM=4096
QEMU_VIDEO_DEVICE=virtio-gpu
```

Ignore the `MAX_JOB_TIME=36000` if you have faster worker (i.e. LPAR) instead of a z/VM.

I hope you will find them helpful.

Thanks!

**Comment by skriesch** [comment]
Hi @LKHN, default our review team wants to see references to valid test runs based on these changes. Can you give us such links, please?

**Comment by LKHN** [comment]
Hi @skriesch , I already shared a single run in the issue:
>An test which does full installation of OS with GUI available on https://openqa.almalinux.org/tests/2601

Please see [AlmaLinux Prerelease s390x](https://openqa.almalinux.org/group_overview/13) Job group at [AlmaLinux openQA](openqa.almalinux.org) for other runs too. Please, let me know anything else needed.

Thanks!

**Comment by okurz** [comment]
Duplicate of https://github.com/os-autoinst/os-autoinst/issues/2246

**Comment by andrewlukoshko** [comment]
@okurz please reopen this issue and close https://github.com/os-autoinst/os-autoinst/issues/2246 instead.
It was abandoned and actual work is going on here.

**Comment by okurz** [comment]
I wonder why you need this specific issue. Only pull requests should matter.

**Comment by LKHN** [comment]
@okurz Since one of the PRs belogs to the openQA repository, not this one. I created to make easier to track the overall status.

**Comment by LKHN** [comment]
Thanks everyone!
