### ISSUE TITLE
os-autoinst-setup-multi-machine uses wrong zone for tap devices

### ISSUE THREAD

**Issue by Vogtinator** [os-autoinst/os-autoinst#2358]
I'm not entirely sure, but don't tapX devices (which use the default zone) have to be in a different zone than the bridge and ethernet?
That's how it's currently setup on openqaworker22 at least.

https://github.com/os-autoinst/os-autoinst/blob/fb060dcf48f248686384ceb380014f71d2e77735/script/os-autoinst-setup-multi-machine#L22

**Comment by okurz** [comment]
> I'm not entirely sure, but don't tapX devices (which use the default zone) have to be in a different zone than the bridge and ethernet? That's how it's currently setup on openqaworker22 at least.

"have to be" as in the communication can not be established or as in "insecure"?

**Comment by Vogtinator** [comment]
The former.

**Comment by okurz** [comment]
well, I could find w22 and w23 with their tap class enabled. And the firewall config looks like this:

w22:

```
public
  interfaces: tap0 .. tap178
trusted
  interfaces: br1 ovs-system br0 eth0
```

w23:

```
public
  interfaces: eth0
trusted
  interfaces: br1 ovs-system tap0 .. tap178 br0
```

so even inconsistent among those both. I would say we are not done yet with knowing if the setup script works but I am sure that devices do not have to be in different zones to be able to communicate.

**Comment by Vogtinator** [comment]
Ok.
