### ISSUE TITLE
Please add copyright holder information

### ISSUE THREAD

**Issue by henrich** [os-autoinst/os-autoinst#261]
Hi,

I've put package request for Debian as http://bugs.debian.org/690244
but one of the blocker is there's no copyright holder information in source.
I should note it in debian/copyright file in certain format, see
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
so, could you help me, please?

**Comment by henrich** [comment]
In COPYING file, "Code in this directory was written by Bernhard M. Wiedemann" but this version of os-autoinst was rewritten, right?

Now who has copyright for this software - SUSE?

**Comment by lnussel** [comment]
Sorry, we overlooked this issue for so long. I think it's mostly
Copyright (C) 2009-2013 Bernhard M. Wiedemann
Copyright (C) 2012-2014 SUSE Linux Products GmbH
Copyright (C) 2015 SUSE Linux GmbH

@bmwiedemann?

**Comment by bmwiedemann** [comment]
So after some further discussion, it seems it should be
```
Copyright (C) 2009-2013 Bernhard M. Wiedemann
Copyright (C) 2012-2015 SUSE LLC
```

**Comment by henrich** [comment]
thanks folks :)
I'll update debian/copyright file and push it to official repository later.
