### ISSUE TITLE
`needle.pm` has a `tags()` method that compares a list named `tags` against a hash called `tags`. This seems unnecessarily confusing

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#295]
......yeeeeeah. I may be missing something here, but I don't think so.  For extra bonus points, it manages to do all that _in the space of four lines!_

https://github.com/os-autoinst/os-autoinst/blob/master/needle.pm#L184

```
sub tags($) {
    my @tags      = split(/ /, shift);
    my $first_tag = shift @tags;
    my $goods     = $tags{$first_tag};
```

**Comment by okurz** [comment]
I agree this could be better. Do you have a proposal or should we just close this and wait until someone refactors the code as part of a bigger change?

**Comment by AdamWill** [comment]
Not right now, but if I ever get some of this mythical 'spare time' I could try and come up with one...

**Comment by coolo** [comment]
As I touched the code, I cleaned this up in https://github.com/os-autoinst/os-autoinst/pull/715
