### ISSUE TITLE
move `INSTLANG` default value to os-autoinst-distri-opensuse

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#297]
os-autoinst `bmwqemu.py` hardcodes a default for `INSTLANG`:

    $vars{INSTLANG}      ||= "en_US";

this isn't really appropriate, as the `INSTLANG` implementation is pretty openSUSE-specific. Could it be moved into os-autoinst-distri-opensuse?

**Comment by okurz** [comment]
I think as no one was objecting so far I'd guess the answer is yes. Maybe provide a PR for os-autoinst-distri-opensuse first, have it merged there to set if not set, then a PR to remove it in os-autoinst.

**Comment by coolo** [comment]
actually our tests never check INSTLANG, so just removing in os-autoinst is fine

**Comment by okurz** [comment]
fixed with https://github.com/os-autoinst/os-autoinst/commit/31392b19a66345dc2d6c69949026eb0309a52f0b

@coolo, @sysrich please close

**Comment by AdamWill** [comment]
I can do that!
