### ISSUE TITLE
hardcoded libexec path in `cv.pm`

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#316]
`cv.pm` has this:

    my $libdir    = dirname(__FILE__);
    return if ($libdir eq "/usr/lib/os-autoinst");

but `Makefile.am` has this:

    pkglibexec_SCRIPTS = \
    ...
    	cv.pm \

libexecdir is not `/usr/lib` everywhere. Fr'instance, on Fedora, it's `/usr/libexec`.

A bad fix for this would be to hack up the test a bit with an `or` or a regex or something. A better fix would be to have the path in `cv.pm` substituted during the build process, I guess. I'll try and come up with a PR for that, just documenting the issues I've run into for now so we don't forget them.

**Comment by coolo** [comment]
you fixed that
