### ISSUE TITLE
[doc] add note that vars.json can be overwritten by test runs -> should use VCS or local copy

### ISSUE THREAD

**Issue by okurz** [os-autoinst/os-autoinst#341]

**Comment by coolo** [comment]
we can have a HACKING.md wich such tips

**Comment by okurz** [comment]
Normally when someone tells "we can" it means "you should do it", but coming from you that normally means "I have already done it it and you will see the PR merged before you even finished writing *this* comment" ;-)

**Comment by coolo** [comment]
your set of rules lacks "coolo + documentation => /dev/null" ;)

**Comment by okurz** [comment]
Fixed with #440
