### ISSUE TITLE
s390: backend tries to create VM snapshots, which is invalid

### ISSUE THREAD

**Issue by okurz** [os-autoinst/os-autoinst#343]
s390 backend tries to create VM snapshots, causing 'DIE backend method not implemented at /usr/lib/os-autoinst/backend/baseclass.pm line 289'. Maybe better message with hint to missing variable required?

**Comment by coolo** [comment]
do me a favor and limit your summaries to 80 chars

**Comment by okurz** [comment]
Problem is: I don't know how to submit the "description" field with my github console client :-)

**Comment by coolo** [comment]
then don't use it

**Comment by okurz** [comment]
I can easily create issues using the "hub" client and the rewrite the issue later on in the browser

**Comment by coolo** [comment]
then use a short summary in your client and then add a description in your browser. But my mail box has your issue with an unbearable subject

**Comment by okurz** [comment]
regarding the issue of creating the issue: Found https://github.com/stephencelis/ghi/ , supports setting title and description in one go. Thanks for the incentive ;-)

**Comment by coolo** [comment]
I solved that by not failing in save, but only in load
