### ISSUE TITLE
autoinst-log.txt isn't displaying quotes in QEMU command properly

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/os-autoinst#396]
I've spend time trying to set variable so that it pass its value to QEMU in quotes - I wanted openQA to run QEMU with `-append 'kernel args'`, but it kept showing `-append kernel args` in autoinst-log.txt. Then I realized that it runs command correctly, but displays it differently (without said quotes).

In short, in autoinst-log.txt, there was:

```
starting: /usr/bin/qemu-system-arm ... -append rw root=LABEL=_/ rootwait -device usb-ehci ...
```

but in fact, it was running:

```
/usr/bin/qemu-system-arm ... -append 'rw root=LABEL=_/ rootwait' -device usb-ehci ...
```

**Comment by coolo** [comment]
It actually runs 
```
'qemu' '-append' 'rw root=LABEL' '-device' 'usb-ehci' 
```

but its a bit ugly to show this way :)

Translated into https://progress.opensuse.org/issues/18464
