### ISSUE TITLE
Where is the definition of the "script_run" ?

### ISSUE THREAD

**Issue by wnereiz** [os-autoinst/os-autoinst#412]
Currently in testapi.pm, the script_run defined as 
`return $distri->script_run($name, $wait);`

But in the lib/susedistribution.pm for distri, there is no definition for it. And there is comment:
~~~
# don't import script_run - it will overwrite script_run from distribution and create a recursion`
~~~
I ask this question because I always failed on running script_run with latest version. It looks like the script can not get the tty0 serial redirection output.

**Comment by coolo** [comment]
you know - you can ask questions in IRC or by email too. No reason to spam the issue tracker. Especially with such things.

susedistribution.pm is a distribution.pm - there you find script_run

**Comment by wnereiz** [comment]
Currently theu script_run does not working. It's always failed to get serial redirection output when running. That is a issue I think.

**Comment by aaannz** [comment]
Pay attention, that you can't do redirection to serialdev in `script_run`. Unless you disable the timeout. Can you provide somewhere implementation of you test? I can't find `zypper_patch.pm` anywhere in tests.

**Comment by wnereiz** [comment]
Thank you . Looks like script_run only provide the function to run a script. The serial redirection will not working.
zypper_patch.pm is during developing, this is one part of codes:
~~~
my $zypper_finish       = qr/^There are some running programs that might use files/m;
script_run("zypper -n patch | tee /dev/$serialdev");
wait_serial($zypper_finish, 500);
~~~
I have to use
~~~
type_string "zypper -n patch| tee /dev/$serialdev\n";
~~~
to replace script_run function to make it working.

**Comment by aaannz** [comment]
Indeed, using `type_string` is the correct way if you `wait_serial` after that.

**Comment by aaannz** [comment]
As @okurz pointed out on IRC, if you only wait until zypper finishes, the better way is to call `assert_script_run 'zypper -n patch'` and don't do any redirection to serial.

**Comment by okurz** [comment]
Try "assert_script_run" which should be equivalent to "type_string" + "wait_serial". I might not solve the issue but be a valid workaround.

**Comment by coolo** [comment]
you can still use script_run with a ,0 argument if you do the waiting yourself

**Comment by wnereiz** [comment]
Thank you. I will try "assert_script_run"
