### ISSUE TITLE
Reporting screen match with needle that is not directly in `needles/` directory fails

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/os-autoinst#426]
Although openQA can (and will) load needles from subdirectories of `needles/` recursively and os-autoinst does match against that needles, writing information about matched needle fails.

At the start of openQA log, there is:

    init needles from /var/lib/openqa/share/tests/fedora/needles
    loaded 272 needles

also, test then starts without problem and shows:

    MATCH(bootloader_uefi:0.00)
    no match 19
    MATCH(bootloader_uefi:0.00)
    no match 18

but after match is found, it fails with:

    MATCH(bootloader_uefi:1.00)
    Can't find /var/lib/openqa/share/tests/fedora/needles/bootloader_uefi.png at /usr/libexec/os-autoinst/needle.pm line 89.
    test _boot_to_anaconda died: Can't call method "has_property" on unblessed reference at /usr/libexec/os-autoinst/basetest.pm line 113.

It can't find `/var/lib/openqa/share/tests/fedora/needles/bootloader_uefi.png` because said needle is in `/var/lib/openqa/share/tests/fedora/needles/console/bootloader_uefi.png`.

It happens in openQA 4.3 with os-autoinst 4.3. Full log is [here](http://fpaste.org/321804/28886814/).

**Comment by okurz** [comment]
So I recommend to change the code as follows:
1. Make openQA read non-recursively
2. Optional: Extend openQA to read from recursive folder structure, which would include the at least following features
 - Load(init) needles from needles directory recursively
 - Extend needle editor to also write in subdirectories
 - … and create dirs if not existing
 - how to handle old test results when the needle paths change?
 - adapt documentation

IHMO this is a feature request which is not an easy task to do right now, better create a ticket here: https://progress.opensuse.org/projects/openqav3/issues/new

**Comment by okurz** [comment]
@garretraziel after #452 is done can you comment the impact on the current issue?

**Comment by garretraziel** [comment]
#452 indeed fixes this problem, although it doesn't implement all necessary functionality you've talked about (it doesn't create directories nor it enables user to create needles in directories, it merely enables you to load from them), but it's good enough for this bug.
