### ISSUE TITLE
Can't exec "multimon": No such file or directory at /usr/lib/os-autoinst/bmwqemu.pm

### ISSUE THREAD

**Issue by 77github** [os-autoinst/os-autoinst#442]
When I use $self->assert_DTMF($expectDTMFCode), the autoinst-log.txt report :
Can't exec "multimon": No such file or directory at /usr/lib/os-autoinst/bmwqemu.pm line 438.
readline() on closed filehandle M at /usr/lib/os-autoinst/bmwqemu.pm line 439

**Comment by coolo** [comment]
Not sure where you're coming from - but assert_DTMF is dead since a3c51303bd90062c330cc6dd03cda511543d8823
