### ISSUE TITLE
Add `assert_reboot`

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#466]
The qemu backend can do `assert_shutdown` by querying the VM's state via QMP. A thing I'd like to be able to do is `assert_reboot`. This would be for automated install tests; I'd like to have a test which simply sits there while the installer is running and waits for the system to reboot. The point would be so _this_ test could be a child of our `anacondatest` base, which uploads a bunch of interesting installer logs when the test fails. Right now, when an automated install test fails, we don't upload any of the installer stuff because the test which waits for the install to complete is technically a post-install test and so is not a child of `anacondatest`. There are other ways to deal with this, but this is the one I like, I think.

There's a dumb way I can do this: just have the test look for a needle that matches the qemu boot screen. But being able to do it properly via QMP would be kinda cooler and more robust, I think.

Digging around to see if this is possible, I found [this nugget](https://serverfault.com/questions/181683/libvirt-qemu-reboot-hook), which suggests qemu sends an async message over QMP when a reboot happens. But I couldn't find a lot more detail. Can we handle those?

**Comment by coolo** [comment]
the qemu backend spits out qemu events into the log and from what I can say there is no such event on reboots. There are events when we load and save vms and there are events when we shutdown, but not when we reset.

So we have a function in our tests to verify the boot menu. the QEMU screen is usually not good enough anyway to upload logs - you'll have to wait for longer to actually be able to do anything with the system. So I'd close this one

**Comment by coolo** [comment]
FYI, this is how it would look like in the log:
03:26:19.7678 EVENT {"event":"RESET","timestamp":{"seconds":1459998079,"microseconds":11554}}

but I only see it on shutdown

**Comment by AdamWill** [comment]
hum, okay. Maybe I'll ask some qemu devs.

For the record, I wouldn't be matching on the boot screen expecting to be able to do anything with the system at *that* point. The point of the match is to know that *before* that point, we're still in the anaconda environment, and thus if we fail at that point we can upload all the interesting bits from the anaconda environment. Right now we don't actually "know" when we're still in the anaconda environment when running a kickstart test, so we never upload anaconda bits on failure for kickstart tests even though we could.

**Comment by okurz** [comment]
Maybe the more recent better support for libvirt in os-autoinst can help with this as AFAIK libvirt can be instructed to fully shut down the node on reboot, e.g. see https://ask.fedoraproject.org/en/question/8796/make-libvirt-to-shutdown-my-guests-not-suspend/

**Comment by coolo** [comment]
Well, passing -no-reboot to qemu would achieve the same. We would have to restart either the libvirt domain or QEMU, but at least on virtual machines we could use this to assert_reboot.

Anyway, please move this to progress.oo if you still believe it can be done.
