### ISSUE TITLE
some tests fail on i586 due to "undefined symbol: _ZTVN2cv11_InputArrayE" in tinycv.so

### ISSUE THREAD

**Issue by doktor5000** [os-autoinst/os-autoinst#493]
When trying to backport os-autoinst to our stable release, Mageia 5 there are some issues with the tests. They try to load ./ppmclibs/blib/arch/auto/tinycv/tinycv.so which has an undefined symbol _ZTVN2cv11_InputArrayE which seems to imply an issue with an opencv library.

failures are as follows:

```
# Compilation of consoles::sshX3270 failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```

```
# Compilation of consoles::vnc_base failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::VNC failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::sshXtermVt failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::localXvnc failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::sshVirtsh failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::remoteVnc failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of consoles::s3270 failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at consoles/VNC.pm line 10.
```
```
# Compilation of ppmclibs::tinycv failed: Can't load './ppmclibs/blib/arch/auto/tinycv/tinycv.so' for module tinycv: ./ppmclibs/blib/arch/auto/tinycv/tinycv.so: undefined symbol: _ZTVN2cv11_InputArrayE at /usr/lib/perl5/5.20.1/i386-linux-thread-multi/DynaLoader.pm line 193, <DATA> line 2125.
#  at /usr/lib/perl5/vendor_perl/5.20.1/Test/Compile/Internal.pm line 198.
```
- build log from i586 build:
http://pkgsubmit.mageia.org/uploads/failure/infra_5/infra/updates/20160507145324.doktor5000.duvel.18846/log/os-autoinst-4.3-1.mga5.infra/build.0.20160507145404.log

- build log, same build but on x86_64, only fails perlcritic run:
http://pkgsubmit.mageia.org/uploads/failure/infra_5/infra/updates/20160507145324.doktor5000.duvel.18846/log/os-autoinst-4.3-1.mga5.infra/build.0.20160507145405.log

Apart from the obvious issue with tinycv.so, would be nice to know how to skip only the perlcritic checks, as those are probably not that relevant to you?

**Comment by doktor5000** [comment]
Spotted what I think is part of the cause, in `ppcmlibs/Makefile.PL` the following is used:

`$opencv_libs =~ s,/usr/lib64/lib(\S+)\.so,-l\1,g;` which will obviously fail on non x86_64 systems, this is the first problem.

The other problem is that the opencv pkg-config file seems to be broken (which is probably why the above regex replacement is necessary in the first place ) whereas it should usually return only the linker flags/library names, it returns full paths:
```
pkg-config --libs opencv
/usr/lib64/libopencv_calib3d.so /usr/lib64/libopencv_contrib.so /usr/lib64/libopencv_core.so /usr/lib64/libopencv_features2d.so /usr/lib64/libopencv_flann.so /usr/lib64/libopencv_gpu.so /usr/lib64/libopencv_highgui.so /usr/lib64/libopencv_imgproc.so /usr/lib64/libopencv_legacy.so /usr/lib64/libopencv_ml.so /usr/lib64/libopencv_nonfree.so /usr/lib64/libopencv_objdetect.so /usr/lib64/libopencv_ocl.so /usr/lib64/libopencv_photo.so /usr/lib64/libopencv_stitching.so /usr/lib64/libopencv_superres.so /usr/lib64/libopencv_ts.so /usr/lib64/libopencv_video.so /usr/lib64/libopencv_videostab.so
```

I've fixed my issue via replacing the /usr/lib64/ part of that regex with the proper value depending on what architecture the build is run via

**Comment by okurz** [comment]
actually when calling `pkg-config --libs opencv` on openSUSE Leap 42.1 the output looks sane, i.e.:
```
$ pkg-config --libs opencv
-lopencv_face -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core
```
so it might be valuable to check why the opencv pkg-config file does not work correctly in your environment. I would be interested how does the output look like in your i586 build environment? Maybe no one minds if we just get rid of this line and you fix it in your specific i586 build instructions.

**Comment by doktor5000** [comment]
Hmmm, so in your example the correct opencv pkconfig libs seem to be coming from this patch which does not come from upstream AFAICT: https://build.opensuse.org/package/view_file/openSUSE:Leap:42.2/opencv/opencv-pkgconfig.patch?expand=1
I'll add this to our opencv packages. Will need to check again for the i586 build output,

**Comment by coolo** [comment]
we actually can remove that workaround, but that means you also need to fix your x86_64 - we actually don't support i586 at all in reality

**Comment by doktor5000** [comment]
Hi Stephan, the x86_64 build works just fine, there's nothing to fix there :)

FWIW regarding my initial remark, perlcritic tests only failed because we had an older version of perlcritic, which seemed to mark some usage of "subroutine signatures" as errors, but newer versions of perlcritic seem to be fine with that.

**Comment by coolo** [comment]
I can't help you here any further. this is a pkg-config vs. opencv problem on your platform that I'm not willing to workaround
