### ISSUE TITLE
`isotovideo` can die unexpectedly when trying to kill autotest process (due to use of `autodie`)

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/os-autoinst#535]
First reported as a follow-up in https://github.com/os-autoinst/os-autoinst/issues/530 , but it's clearly not actually the same issue, so filing it separately.

8a1561729647b2f775410cdb4c7081809abcb8f7 made `isotovideo` use the `autodie` module, which basically causes lots of perl system calls that usually return on error to die on error instead. This means that when `isotovideo` makes an unguarded attempt to kill the autotest process:

    close $testfd;
    kill('SIGTERM', $testpid);
    diag "awaiting death of testpid $testpid";
    waitpid($testpid, 0);

if that process had actually already gone away, `isotovideo` will immediately die unexpectedly. This may cause the worker service to fail the next time it gets a job, because the VM process may not yet have been killed before `isotovideo` dies (it calls `bmwqemu::stop_vm();` after this), so when it tries to start a new job the worker will hit the infamous `QEMU should be dead - WASUP?` and die. This "kill autotest" code is new in 66427507185b714c9c9b433c0b0a8d136f46af9b , so the bug likely didn't occur before that.

Here's an affected job: https://openqa.stg.fedoraproject.org/tests/28028

Here's the job logs at the end:

    11:53:51.0978 30389 >>> testapi::_check_backend_response: found desktop_clean, similarity 1.00 @ 3/739
    11:53:51.0988 30389 ||| finished _graphical_wait_login tests at 2016-07-09 11:53:51 (200 s)
    11:53:51.0991 30389 Creating a VM snapshot lastgood
    11:54:01.1243 30391 SAVED lastgood savevm lastgood
    11:54:01.1252 30384 sysread failed: 
    11:54:01.1272 30384 30384: got sigchld
    11:54:01.1274 30384 THERE IS NOTHING TO READ 12 12 11
    Can't kill('SIGTERM', '30389'): No such process at /usr/bin/isotovideo line 345
    +++ worker notes +++
    end time: 2016-07-09 11:54:01
    result: died
    uploading video.ogv
    uploading vars.json
    uploading serial0.txt
    uploading autoinst-log.txt

It's the `Can't kill('SIGTERM', '30389'): No such process at /usr/bin/isotovideo line 345` line which is the distinctive behaviour of `autodie`, without `autodie`, you wouldn't get that. At that point `isotovideo` dies.

Here's the journal from the worker host:

    Jul 09 11:36:18 qa06.qa.fedoraproject.org worker[10441]: 30384: WORKING 28028
    Jul 09 11:54:01 qa06.qa.fedoraproject.org worker[10441]: child 30384 died with exit status 768
    Jul 09 11:54:01 qa06.qa.fedoraproject.org worker[10441]: killing 30384
    Jul 09 11:54:01 qa06.qa.fedoraproject.org worker[10441]: waitpid returned error: No child processes
    Jul 09 11:59:06 qa06.qa.fedoraproject.org worker[10441]: cleaning up 00028028-fedora-Rawhide-KDE-live-iso-i386-BuildFedora-Rawhide-20160709.n.0-install_default@64bit...
    Jul 09 11:59:06 qa06.qa.fedoraproject.org worker[10441]: duplicating job 28028
    Jul 09 11:59:06 qa06.qa.fedoraproject.org worker[10441]: QEMU (30396 -> /usr/bin/qemu-system-x86_64) should be dead - WASUP?
    Jul 09 11:59:07 qa06.qa.fedoraproject.org systemd[1]: openqa-worker@4.service: Main process exited, code=exited, status=1/FAILURE

@coolo (changed all this shutdown code), @okurz (added the `autodie` use)

**Comment by okurz** [comment]
like shell scripts with `#!/bin/sh -e` I'd like to always see fatal errors in case of not explicitly checked return codes. Yes, also when terminating processes. However, it might make sense to add cleanup code which is automatically called when the current scope of code exits abnormally.

**Comment by coolo** [comment]
fixed in https://github.com/os-autoinst/os-autoinst/pull/534

**Comment by AdamWill** [comment]
Isn't it a bit premature to close issues for a PR that isn't reviewed yet?

**Comment by coolo** [comment]
an open pull request is also an issue - and I don't need dups
