### ISSUE TITLE
What are typed by type_string on ipmi physical machine is not correct.

### ISSUE THREAD

**Issue by alice-suse** [os-autoinst/os-autoinst#555]
Fail stage: host installation
Fail reason: what are typed out by type_string is not right

It started to happen from build 2016,  and can be seen in all following builds. It happened randomly in testsuites in test group 46 virtualization.

Typical failure links:
https://openqa.suse.de/tests/497262#step/skip_registration/6
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP2&build=2016&groupid=46

**Comment by coolo** [comment]
you better make this a progress item - as you say yourself it started with a build, tracking this as os-autoinst problem doesn't sound proper. I claim that the keyboard driver of the product is buggy.
