### ISSUE TITLE
NICTYPE_USER_OPTIONS does not affect `-netdev user` on PPC & AARCH64

### ISSUE THREAD

**Issue by mnowaksuse** [os-autoinst/os-autoinst#557]
From some reason `NICTYPE_USER_OPTIONS` (added with https://github.com/os-autoinst/os-autoinst/pull/547) is not being added to `-netdev user` Qemu option on PPC and AARCH64: https://openqa.suse.de/tests/502320 and https://openqa.suse.de/tests/502215. However it works on x86-64: https://openqa.suse.de/tests/502553/file/autoinst-log.txt. There I get `-netdev user,id=qanet0,hostname=dhcphostname`.

It's either some old version of os-autoinst on PPC and AARCH64 workers, or I don't understand the code paths in `backend/qemu.pm` affecting `-netdev user` correctly.

**Comment by okurz** [comment]
I recommend you exclude non-x86_64 from tests for now and link the `if` to this issue until it's solved.

**Comment by mnowaksuse** [comment]
Removed the test from `yast_hostname+dhcp_hostname` scenario as the test fails only there, and works in other scenarios on those archs.

**Comment by coolo** [comment]
Hard to say what happened 400T jobs ago :)
