### ISSUE TITLE
empty ENV{QEMU} make ppc64le worker to use qemu-system-x86_64

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/os-autoinst#601]
after install of openQA and os-autoinstall in a ppc64le TW host following doc (1)
the worker is abnormally trying to use qemu-system-x86_64 rather than qemu-system-ppc64
This is related to backend/qemu.pm (2) and presence of qemu-x86 rpm in my host install (3)

my current bypass is to remove the qemu-x86 rpm
But is it possible to have the install procedure of openQA/os-autoinstall
to add a 'valid' QEMU setup ?

(1) https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc
(2) https://github.com/os-autoinst/os-autoinst/blob/master/backend/qemu.pm#L227
(3) 
```
 qemu-x86 installed also on ppc64le host:
===
$rpm -qa |grep qemu
qemu-seabios-1.9.1-1.2.noarch
qemu-x86-2.6.1-1.1.ppc64le
qemu-vgabios-1.9.1-1.2.noarch
qemu-2.6.1-1.1.ppc64le
qemu-tools-2.6.1-1.1.ppc64le
qemu-linux-user-2.6.1-1.1.ppc64le
qemu-ppc-2.6.1-1.1.ppc64le
libvirt-daemon-driver-qemu-2.2.0-1.1.ppc64le
qemu-ipxe-1.0.0-1.2.noarch
qemu-block-curl-2.6.1-1.1.ppc64le
qemu-sgabios-8-1.2.noarch
qemu-ksm-2.6.1-1.1.ppc64le
===
```

**Comment by aaannz** [comment]
You can also add QEMU variable to Machines table `QEMU=qemu-system-ppc64`.
I suppose we can prioritize which QEMU binary to use by depending on the host arch.

**Comment by michelmno** [comment]
I did a trial adding ```QEMU=qemu-system-ppc64``` to the ppc64 and ppc64 machines via the webui interface (1) but even after a host reboot, the worker is still reporting invalid qemubin variable
as per debugmno traces (2)

(1) openqa_url/admin/machines
```
ppc64le	qemu	
OFW=1
QEMU=qemu-system-ppc64
QEMUCPU=host
VGA=std
WORKER_CLASS=qemu_ppc64le
===	
ppc64	qemu	
OFW=1
QEMU=qemu-system-ppc64
QEMUCPU=host
VGA=std
WORKER_CLASS=qemu_ppc64
```

(2) http://paste.opensuse.org/view/raw/23823069
```
15:41:09.0610 2467 start_qemu debugmno qemubin ; as set from ENV(QEMU)
15:41:09.0611 2467 start_qemu debugmno check access /usr/bin/kvm
15:41:09.0611 2467 start_qemu debugmno check access /usr/bin/qemu-kvm
15:41:09.0612 2467 start_qemu debugmno check access /usr/bin/qemu
15:41:09.0612 2467 start_qemu debugmno check access /usr/bin/qemu-system-x86_64
15:41:09.0612 2467 start_qemu debugmno qemubin /usr/bin/qemu-system-x86_64
```

**Comment by aaannz** [comment]
Looking at the code
```perl
my @candidates = $vars->{QEMU} ? ('qemu-system-' . $vars->{QEMU}) : qw/kvm qemu-kvm qemu qemu-system-x86_64 qemu-system-ppc64/;
```
the variable should be `QEMU=ppc64`.

Did you just restart the job or scheduled? Restarting it does not update variables used in previous run. You need to schedule it as new.

**Comment by michelmno** [comment]
@aaannz what is the way to "need to schedule it as new" ? is there a way to do that via the webui ?
What I just did was  to call /var/lib/openqa/script/client with related parameters,
and that solved my problem.
I am find with your proposal to add QEMU to Machine tables, and I submitted above PR.

**Comment by aaannz** [comment]
Only calling client script with `jobs post` or `isos post` and related parameters. WebUI can only clone (restart) existing jobs which doesn't update used variables.
There is a possibility to reschedule complete product via 'Scheduled products' menu which updates variables taken from tables.

**Comment by michelmno** [comment]
close issue with merge of PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/issues/1852
