### ISSUE TITLE
webserver died "Address family for hostname not supported"

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/os-autoinst#602]
after install of openQA and os-autoinst in a ppc64le TW host
the worker is unable to start the Mojo webserver with traces extracted in (1)

the local bypass is to force 127.0.0.1 listen address in
commands.pm:259 my $daemon = Mojo::Server::Daemon->new(app => app, listen => ["http://127.0.0.1:$port"]);

Current behaviour is a side-effect of previous corrections of issue #589 #585

I do not understand current failure while setup of issue #589 seems to fit what is documented in Mojo documentation (2)

(1)

```
[Tue Sep 20 13:50:31 2016] [info] Daemon reachable under http://*:20023/2xqdREfJ_jeiLRwm/
failed to run daemon Can't create listen socket: Address family for hostname not supported at /usr/lib/perl5/vendor_perl/5.24.0/Mojo/IOLoop.pm line 122.

11:50:31.5074 42573 got sigchld
11:50:31.5075 42573 commands webserver died
```

(2) http://www.mojolicious.org/perldoc/Mojo/Server/Daemon

```
# Listen on all IPv4 and IPv6 interfaces
$daemon->listen(['http://[::]:3000']);
```

(3)

```
$rpm -qa |grep autoinst
os-autoinst-4.4.1474276783.212cb04-0.ppc64le
$rpm -qa |grep -i mojo
perl-Mojolicious-Plugin-AssetPack-1.17-1.1.noarch
perl-Mojolicious-7.06-115.1.noarch
perl-Mojolicious-Plugin-RenderFile-0.10-1.3.noarch
```

**Comment by coolo** [comment]
does this mean you're not having IPv6?

**Comment by michelmno** [comment]
correct I am currently testing on a machine without IPV6 network.

**Comment by kraih** [comment]
Guess it could use a check like `IO::Socket::IP->new(Listen => 5, LocalAddr => "[::]") ? "[::]" : "0.0.0.0"`.

**Comment by coolo** [comment]
https://github.com/os-autoinst/os-autoinst/pull/618 then

**Comment by michelmno** [comment]
I will test with last changes and close this issue when will be back from vacation in november.

**Comment by michelmno** [comment]
verified OK with last retrieved openQA:
$rpm -qa |grep -E 'openQA|autoinst' |sort
openQA-4.4.1477579540.21d4009-27.1.noarch
openQA-client-4.4.1477579540.21d4009-27.1.noarch
openQA-common-4.4.1477579540.21d4009-27.1.noarch
openQA-worker-4.4.1477579540.21d4009-27.1.noarch
os-autoinst-4.4.1477584874.4e2d106-155.1.ppc64le
