### ISSUE TITLE
ipmi backend: test  incomplete due to code not robust enough to power on machine at test beginning

### ISSUE THREAD

**Issue by alice-suse** [os-autoinst/os-autoinst#603]
Issue:
IPMI backend needs to handle temporary ipmi session establishment problems to make test more robust.

Test link:
https://openqa.suse.de/tests/586661/file/autoinst-log.txt

Job build link:
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP2&build=2140&groupid=46

Key error log:
12:04:38.1385 2809 IPMI: Chassis Power Control: Down/Off
12:04:38.1681 2809 IPMI: Chassis Power is off
12:04:38.1968 2809 IPMI: Chassis Power Control: Up/On
12:04:38.2270 2809 IPMI: Chassis Power is off
12:04:38.2573 2809 IPMI: Chassis Power Control: Up/On
12:04:40.2889 2809 IPMI: Chassis Power is off
12:04:40.3201 2809 IPMI: Chassis Power Control: Up/On
 Error: Unable to establish LAN session at /usr/lib/os-autoinst/backend/ipmi.pm line 62.

**Comment by coolo** [comment]
would be cool if you couldn't post passwords in public issue trackers

**Comment by alice-suse** [comment]
Sorry for not noticing, removed it.

**Comment by aaannz** [comment]
You know its too late. There are plenty of bots listening to github feeds. Once posted, they have it. I suggest to change them asap.

**Comment by coolo** [comment]
it's not really a high critical password, as you can't access these machines from anywhere but the QA sub network. But still it's good habit double check what you post publically.
