### ISSUE TITLE
[ipmi] wait_serial does not get expected output because ipmi console connection is closed

### ISSUE THREAD

**Issue by alice-suse** [os-autoinst/os-autoinst#605]
Test failed due to wait_serial does not get output. From serial0.txt, the ipmi session was already closed due to "excess errors received"

Failure step:
https://openqa.suse.de/tests/587781#step/install_package/4

Build link: 
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP2&build=2141&groupid=46

Serial output link:
https://openqa.suse.de/tests/587781/file/serial0.txt

Key serial output errors:

[[0;32m  OK  [0m] Started Serial Getty on ttyS1.

[[0;32m  OK  [0m] Started Serial Getty on hvc0.

         Starting X Display Manager...

[[0;32m  OK  [0m] Started Getty on tty1.

[[0;32m  OK  [0m] Reached target Login Prompts.

[[0;32m  OK  [0m] Started /etc/init.d/after.local Compatibility.

[[0;32m  OK  [0m] Started Load dom0 backend drivers.

         Starting The Xen xenstore...

[SOL established]

[error received]: excess errors received

[closing the connection]

**Comment by okurz** [comment]
Please use https://progress.opensuse.org/projects/openqatests/issues/ for test issues. If we come to the conclusion it's the backend we can easily move the ticket to https://progress.opensuse.org/projects/openqav3/issues/

IMHO the test should already fail in https://openqa.suse.de/tests/587781#step/login_console/9 as there is no point to continue when the serial port forwarding does not work.

**Comment by alice-suse** [comment]
It depends on when the connection is broken.

**Comment by alice-suse** [comment]
Ok, will move the issue to  https://progress.opensuse.org/projects/openqatests/issues/.

**Comment by alice-suse** [comment]
Ok, will move the issue to  https://progress.opensuse.org/projects/openqatests/issues/.
