### ISSUE TITLE
qemu backend: specifying boot order with -boot order=X doesn't work with UEFI/OVMF

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/os-autoinst#640]
This applies to Fedora with os-autoinst-4.4, qemu-2.6.2 and both edk2-ovmf-20160418gita8c39ba (from Fedora stable repos) and newest edk2-ovmf from github, but I suppose that this is also true for openSUSE.

tl;dr: `-boot order=X` that os-autoinst uses for specifying what to boot doesn't really work on UEFI (at least on Fedora). We should replace it with `bootindex=0` on the device we want to boot from. We should also consider adding support for handling `OVMF_VARS.fd`.

Long story:
os-autoinst is using qemu parameter `-boot order=c` to boot from disk, `-boot order=d` to boot from cdrom and `-boot once=d` to boot from cdrom on the first boot, but from disk after that. os-autoinst is also using the same parameters for handling UEFI boot order and it seemingly works, except that it doesn't. UEFI support is provided by OVMF and if we look into qemu+ovmf whitepaper [here](http://www.linux-kvm.org/downloads/lersek/ovmf-whitepaper-c770f8c.txt), we can see that `-boot order=X` is legacy command option for UEFI and also, after trying it on Fedora, it doesn't work for me at all. The same documentation also mentions that we should add `bootindex=X` to devices to specify boot order instead.

OVMF boots from cdrom by default and during installation, when bootloader is installed, installator adds new boot option for OS and sets it as default option, so it fortunately behaves like specifying `-boot once=d` out of the box. Problem is when you want to boot from disk - when user wants to boot from disk, we should add `bootindex=0` to first connected disk.

Another problem is with efivars. On UEFI, boot items and their order are specified by so called efivars and these are placed in the same flash memory as UEFI and are shared for the whole computer. In qemu, when user doesn't attach memory for efivars separately, it seems like changes to efivars are stored only temporarily and are lost after VM is shut down. It means that if openQA schedules consecutive test that uses disk from previous UEFI installation, efivars are set to default again (so any boot menu items that were added during installation are lost). When UEFI/OVMF doesn't obtain information about what file to boot from efivars, it uses fallback path \EFI\BOOT\BOOTX64.efi (but this fallback is [currently broken on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1196114)). OVMF+qemu fortunately supports [separating UEFI and efivars](http://vfio.blogspot.cz/2014/09/ovmf-split-image-support.html), so we should consider adding this into openQA - when VM with UEFI is run, OVMF_VARS.fd is copied into test directory and when openQA reuses UEFI disk in another test, it should also link OVMF_VARS.fd from previous test.

Lastly, I've seen some weird behaviour with Fedora's "stable" OVMF (it ignored bootindex sometimes, even with virt-manager). It also somehow retains boot order from previous run, so it looks like specifying `bootindex=0` on disk results in disk being default option even on next runs. I'd appreciate if someone would test OVMF's behaviour on his machine

**Comment by garretraziel** [comment]
If you want to try how qemu behaves with OVMF, use:

    /usr/bin/qemu-kvm -vga qxl -m 2048 -device virtio-scsi-pci,id=scsi0 -device virtio-blk,drive=hd1,bootindex=0 -drive file=disk.qcow2,cache=unsafe,if=none,id=hd1,format=qcow2 -drive media=cdrom,if=none,id=cd0,format=raw,file=cd.iso,snapshot=on -device scsi-cd,drive=cd0,bus=scsi0.0 -bios /usr/share/edk2.git/ovmf-x64/OVMF_CODE-pure-efi.fd -device usb-ehci -device usb-tablet -smp 2 -enable-kvm

**Comment by okurz** [comment]
#641 is merged, is this done?

**Comment by garretraziel** [comment]
Not entirely (I still think that we should consider handling OVMF_VARS.fd), but with #641 it works good enough.

**Comment by coolo** [comment]
good enough is good enough for me.
