### ISSUE TITLE
qemu backend does not handle CDMODEL=virtio-blk-device correctly

### ISSUE THREAD

**Issue by StefanBruens** [os-autoinst/os-autoinst#758]
A openQA default installation with templates taken from https://github.com/os-autoinst/os-autoinst-distri-opensuse/tree/master/products/opensuse
sets CDMODEL to virtio-blk-device

This is not handled correctly in https://github.com/os-autoinst/os-autoinst/blob/master/backend/qemu.pm#L622 as it adds "bus=scsi0.0"

**Comment by coolo** [comment]
please report issues on https://progress.opensuse.org/projects/openqav3/issues 

And I can find virtio-blk-device only on some aarch64 machine
